/bin/
/builds/
/logs/
/reports/
/vendor/

# The following files are excluded from version control because they contain
# sensitive information.
credentials.sh
env.local.secrets.sh
secrets.envrc

# The following files are excluded from version control because they are used
# by developers for scratch work.
TODO.md

# The following files are excluded from version control because they are
# generated by build, test, deployment, and pipeline tooling.
**/*.generated.json
**/*.generated.txt
cover*.html
cover*.out
*-test-report.xml
tests-*.html
tests-*.out

# Created by https://www.gitignore.io/api/go,node,serverless,intellij+all,visualstudiocode

### Go ###
# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, build with `go test -c`
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

### Intellij+all ###
# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio and Webstorm
# Reference: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

.idea/**/vcs.xml
.DS_Store

# User-specific stuff:
.idea/**/workspace.xml
.idea/**/tasks.xml
.idea/dictionaries

# Sensitive or high-churn files:
.idea/**/dataSources/
.idea/**/dataSources.ids
.idea/**/dataSources.xml
.idea/**/dataSources.local.xml
.idea/**/sqlDataSources.xml
.idea/**/dynamic.xml
.idea/**/uiDesigner.xml

# Gradle:
.idea/**/gradle.xml
.idea/**/libraries

# CMake
cmake-build-debug/

# Mongo Explorer plugin:
.idea/**/mongoSettings.xml

## File-based project format:
*.iws

## Plugin-specific files:

# IntelliJ
/out/

# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Cursive Clojure plugin
.idea/replstate.xml

#