@base = https://2afo7guwib.execute-api.us-east-1.amazonaws.com/latest/

GET {{base}}
###

GET {{base}}/pizzas
###

GET {{base}}/pizzas/1
###

GET {{base}}/orders
###

GET {{base}}/orders/1
###

POST {{base}}/orders
Content-Type: application/json

{
  "pizza": 5,
  "address":" 221b Baker Street"
}
###

PUT {{base}}/orders/aa17e0a4-1908-40b4-a8a8-3ad8ee879bba
Content-Type: application/json

{
  "pizza": 5,
  "address":" 1234 Sesame Street"
}
###

DELETE {{base}}/orders/2ab7a874-4600-4377-abb6-09ca8d6e753b